/* Copyright (C) 2015 Jesse Busman
/* You may not distribute this program or parts of this
/* program in any way, shape or form without written
/* permission from Jesse Busman (born 17 march 1996).
/* This program is distributed in the hope that it will
/* be useful, but WITHOUT ANY WARRANTY; without even the
/* implied warranty of MERCHANTABILITY or FITNESS FOR A
/* PARTICULAR PURPOSE. This message may not be changed
/* or removed. */

#ifndef css_properties_included
#define css_properties_included yes

enum CSSProperty
{
	NONE=0,
	
	// CSS1
	COLOR,
	OPACITY,
	
	BACKGROUND_ATTACHMENT,
	BACKGROUND_COLOR,
	BACKGROUND_IMAGE,
	BACKGROUND_POSITION_X, BACKGROUND_POSITION_Y,
	BACKGROUND_REPEAT,
	
	BORDER_BOTTOM_COLOR,
	BORDER_BOTTOM_STYLE,
	BORDER_BOTTOM_WIDTH,
	BORDER_TOP_COLOR,
	BORDER_TOP_STYLE,
	BORDER_TOP_WIDTH,
	BORDER_LEFT_COLOR,
	BORDER_LEFT_STYLE,
	BORDER_LEFT_WIDTH,
	BORDER_RIGHT_COLOR,
	BORDER_RIGHT_STYLE,
	BORDER_RIGHT_WIDTH,
	
	BORDER_TOP_LEFT_RADIUS,
	BORDER_TOP_RIGHT_RADIUS,
	BORDER_BOTTOM_LEFT_RADIUS,
	BORDER_BOTTOM_RIGHT_RADIUS,
	
	CLEAR,
	DISPLAY,
	FLOAT,
	
	HEIGHT,
	WIDTH,
	
	PADDING_BOTTOM,
	PADDING_LEFT,
	PADDING_RIGHT,
	PADDING_TOP,
	
	VERTICAL_ALIGN,
	
	MARGIN_BOTTOM,
	MARGIN_LEFT,
	MARGIN_RIGHT,
	MARGIN_TOP,
	
	LETTER_SPACING,
	LINE_HEIGHT,
	TEXT_ALIGN,
	TEXT_TRANSFORM,
	TEXT_INDENT_LENGTH, TEXT_INDENT_TYPE,
	
	WHITE_SPACE,
	WORD_SPACING,
	TEXT_DECORATION_LINE,
	TEXT_DECORATION_STYLE,
	TEXT_DECORATION_COLOR,
	
	FONT_FAMILY,
	FONT_SIZE,
	FONT_STYLE,
	FONT_VARIANT,
	FONT_WEIGHT,
	
	LIST_STYLE_IMAGE,
	LIST_STYLE_POSITION,
	LIST_STYLE_TYPE,
	
	
	// CSS2
	CLIP,
	
	BOTTOM,
	TOP,
	LEFT,
	RIGHT,
	
	POSITION,
	VISIBILITY,
	Z_INDEX,
	
	MAX_HEIGHT,
	MAX_WIDTH,
	MIN_HEIGHT,
	MIN_WIDTH,
	
	//OVERFLOW,
	
	DIRECTION,
	UNICODE_BIDI, // wtf is this shit, srsly.
	BORDER_COLLAPSE,
	BORDER_SPACING,
	CAPTION_SIDE,
	EMPTY_CELLS,
	TABLE_LAYOUT,
	
	COUNTER_INCREMENT,
	COUNTER_RESET,
	
	CONTENT,
	CURSOR,
	
	OUTLINE_COLOR,
	OUTLINE_STYLE,
	OUTLINE_WIDTH,
	
	WIDOWS,  // lol
	ORPHANS, // wut
	
	PAGE_BREAK_AFTER,
	PAGE_BREAK_BEFORE,
	PAGE_BREAK_INSIDE,
	
	QUOTES,
	
	// CSS3
	/*
	BACKGROUND_CLIP,
	BACKGROUND_ORIGIN,
	BACKGROUND_SIZE,
	
	BORDER_BOTTOM_LEFT_RADIUS,
	BORDER_BOTTOM_RIGHT_RADIUS,
	BORDER_TOP_LEFT_RADIUS,
	BORDER_TOP_RIGHT_RADIUS,
	
	// TODO: add border image stuff
	
	BOX_DECORATION_BREAK,
	BOX_SHADOW,
	
	OVERFLOW_X,
	OVERFLOW_Y,
	
	ALIGN_CONTENT,
	ALIGN_ITEMS,
	ALIGN_SELF,
	
	FLEX,
	FLEX_BASIS,
	FLEX_DIRECTION,
	FLEX_FLOW,
	FLEX_GROW,
	FLEX_SHRINK,
	FLEX_WRAP,
	
	JUSTIFY_CONTENT,
	
	ORDER,
	
	HANGING_PUNCTUATION,
	HYPHENS,
	
	// TODO: add the other CSS3 properties
	
	*/
	
	COMBOS=55555,
	
	BACKGROUND,
	OUTLINE,
	
	BORDER,
	BORDER_COLOR,
	BORDER_WIDTH,
	BORDER_STYLE,
	BORDER_LEFT,
	BORDER_RIGHT,
	BORDER_BOTTOM,
	BORDER_TOP,
	
	BORDER_RADIUS,
	
	LIST_STYLE,
	PADDING,
	MARGIN,
	FONT,
	TEXT_DECORATION,
	
	// These ones are not actually combos, but kinda
	TEXT_INDENT,
	BACKGROUND_POSITION,
};

#endif
